Add testing with molecule and refactor code
egi-qc/ansible-umd pull request #1
Opened 2018-03-21 17:32 UTC by brucellino

Major changes:

  - Add molecule with default scenario
    - test coverage only includes CEntOS7
    - test coverage only includes default file existence
  - Refactor tasks:
    - Include OS-specific variables before OS-specific tasks
    - Change syntax of task inclusion from include: to include_tasks:
    - Change failure message condition to check if the release version
      exists for the OS

2018-06-04 15:38 UTC, orviz commented on vars/Debian9.yml
> +nick: squeeze
nick is not good

2018-06-04 15:38 UTC, orviz commented on vars/Debian8.yml
> +nick: squeeze
nick is not good

2018-06-04 15:38 UTC, orviz commented on vars/Debian7.yml
> +nick: squeeze
nick is not good

2018-06-04 15:39 UTC, orviz requested changes
re-check nick names

2018-06-15 15:54 UTC, gwarf commented on .travis.yml
> +- ruby --versio:
Doesn't look right.

2018-06-15 17:01 UTC, brucellino commented on .travis.yml
> +- ruby --versio:
good catch! thanks.

2022-07-21 13:29 UTC, closed without merging